# Generated by Django 5.0.3 on 2024-05-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.ImageField(null=True, upload_to='mobiles/'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='image',
            field=models.ImageField(null=True, upload_to='smartwatches/'),
        ),
    ]
